### PR TITLE
code update

### PR DESCRIPTION
**Pull request by ZTWHHH**
Upload the tag_identify code and Stanford Named Entity Recognizer package.  
The code is good to work on tag_identify from csv file, it can write the identified data into file automatically.

### CODE REVIEW

**Comment by royceschultz** [comment]
Is there a run-able file?
When I called the function manually, I got an error because I was missing a Java command line dependency. I think spacy is a better model because the model can be downloaded via a python command and there's no java dependency.
Typically these models detect entities based on context, but the data in the cells doesn't have context the same way a sentence would. I think applying the model in this way is not the expected use case and may cause weird errors.
Chase's implementation in #6 seems to work pretty well just using pattern matching.

**Comment by ZTWHHH** [comment]
> 
This is a run-able file, I can run it without mistake on PyCharm with anaconda 3 environment, I don't know why you got a error. I have try the spacy, it also a useful tool, I can fix the code with spacy.
I don't think there are any different between data in cell and sentence. For the first step of of these model to identify, we need get the string, it would not difficult for us to transfer data to string.
Chase's method is clever and clear, it can work on our data very good. But I think it has a limtation about accuracy, especially when work on complex data.

**Comment by royceschultz** [comment]
I had to add the filename of the csv to the script to run it.
I think the issue is a system level dependency on Java to run the model. Python is only used to call the java functions.
It's not about the datatype in the cell. The content of the sentence gives context to the word, but the words in the cells have little to no grammatical meaning, so it can't read the context. My guess is the model is basically doing a dictionary lookup for names rather than entity recognition on sentence context like intended.
Yeah Chace's method won't generalize to all patterns, but it seems to work well in the 5000 cases we have. Maybe take a look at his code and try to correct any errors or make it more generalizable.

**Comment by royceschultz** [comment]
Closing because Chace's method work pretty well without extra dependencies.

**Pull request closed without merging**
